raystack/guardian

app/server.go, domain/provider.go, provider/grafana/client.go, provider/grafana/config.go, provider/grafana/config_test.go, provider/grafana/errors.go, provider/grafana/provider.go, provider/grafana/resource.go
Added provider configuration for grafana:
- Credentials config
- Permission config
=> Grafana Provider

app/server.go, domain/provider.go, provider/tableau/client.go, provider/tableau/config.go, provider/tableau/config_test.go, provider/tableau/errors.go, provider/tableau/provider.go, provider/tableau/resource.go
Added provider config for tableau
=> feat: add provider config for tableau

app/server.go, domain/provider.go, provider/tableau/client.go, provider/tableau/config.go, provider/tableau/config_test.go, provider/tableau/errors.go, provider/tableau/provider.go, provider/tableau/resource.go
Add support for tableau flow access
=> feat: add flow resource

provider/bigquery/provider.go, provider/metabase/provider.go, provider/metabase/provider_test.go, provider/service.go, provider/service_test.go, provider/tableau/provider.go, provider/tableau/provider_test.go
Closes https://github.com/odpf/guardian/issues/62
Changes:
1. trigger fetch resources once provider created
2. fetch only registered resource types
=> feat(provider): only fetch resource types that are added in provider config

domain/appeal.go, domain/approval.go, domain/approver.go, domain/policy.go, domain/provider.go, domain/resource.go
closes #84 
Fixed by only adding `omitempty` to the json and yaml annotation in the policy struct
=> fix: fix policy creation timestamp

appeal/service.go, appeal/service_test.go, approval/service.go, domain/appeal.go
=> fix(appeal): immediately activate appeal if all the approvals passed/approved during the creation

cmd/appeal.go, cmd/policy.go, cmd/provider.go, cmd/resource.go, cmd/root.go, main.go
- Fix usage guide on the wrong command. 
- Improve appeal help messages.
=> feat(cli): improve appeal help messages

.goreleaser.yaml, Makefile, build.go, cmd/root.go, cmd/version.go, go.mod, go.sum
Add version command to return version of guardian client.
=> feat: add version command

api/handler/v1beta1/grpc.go, app/server.go, go.mod, go.sum
- ignore unknown fields from request payload proto 
- add server requests log
=> chore: server enhancements

cmd/policy.go, cmd/provider.go, cmd/utils.go, go.mod
- `guardian policy plan -f=<file-name>`
- `guardian policy apply -f=<file-name>`
- `guardian provider plan -f=<file-name>`
- `guardian provider apply -f=<file-name>`
=> feat(cli): add `plan` and `apply` command for provider & policy

go.mod, store/postgres/store.go
=> fix: handle empty postgres password

Dockerfile
* Add curl and open ssl
* Get certificates from authority for openIDM
* Decode cert file to .pem file
=> feat: add curl and openssl to image

.gitignore, core/appeal/service.go, core/appeal/service_test.go, jobs/handler.go
=> fix: terminate old active appeal

core/appeal/mocks/notifier.go, core/appeal/service.go, go.mod, go.sum, jobs/appeal_expiration_reminder.go, mocks/Notifier.go, plugins/notifiers/client.go, plugins/notifiers/slack/client.go
=> fix(notifiers): send notifications for each user and print errors at last

domain/provider.go, internal/server/server.go, internal/server/services.go, plugins/providers/noop/config.go, plugins/providers/noop/provider.go, plugins/providers/noop/provider_test.go, plugins/providers/noop/resource.go
=> feat(provider): introduce no-op provider

core/appeal/service.go
=> feat: add account_id to revoke notification variables

core/provider/service.go, internal/store/postgres/resource_repository.go, internal/store/postgres/resource_repository_test.go
Fix [update resource metadata](https://github.com/odpf/guardian/issues/208)
=> fix: update resource metadata on refresh (#208)

docs/docs/guides/configuration.md
Docs update for this issue #191
=> docs(configuration): update cron jobs in server config

core/appeal/service.go
=> chore: add invalid duration value in error

internal/server/server.go, jobs/fetch_resources.go
=> fix(jobs): run all enabled jobs

internal/store/postgres/migrations/000005_add_permissions_to_appeal.up.sql
closes #270 
* fix(appeal): fix 'permissions' column addition migration script #273
=> fix(appeal): merge fix permissions migration script from `v0.3.6` to `main`

internal/store/postgres/migrations/000008_move-access-management-to-grant.down.sql, internal/store/postgres/migrations/000008_move-access-management-to-grant.up.sql
this change is missed from the previous PR (#277)
=> fix: fix appeal-grant migration script

api/handler/v1beta1/adapter.go, api/handler/v1beta1/grant.go, cli/job.go, core/grant/service.go, go.sum, internal/store/postgres/migrations/000007_create_grants_table.up.sql, internal/store/postgres/migrations/000008_move-access-management-to-grant.up.sql, jobs/grant_expiration_reminder.go
Fix [issues](https://github.com/odpf/guardian/issues/296)
=> fix: fix guardian issues

core/provider/service.go, core/provider/service_test.go
=> fix: fetch provider resources incrementally 

Makefile, api/handler/v1beta1/policy.go, api/handler/v1beta1/provider.go, cli/policy.go, cli/provider.go, core/policy/service.go, core/policy/service_test.go, core/provider/service.go, core/provider/service_test.go
Closes: https://github.com/odpf/guardian/issues/128
Proton PR: https://github.com/odpf/proton/pull/221
=> feat: support dry run create and update policy and provider

core/appeal/service.go, core/grant/service.go, docs/docs/reference/configuration.md, domain/notifier.go, jobs/grant_expiration_reminder.go
=> feat: add account_id to notification variables

go.mod, go.sum, internal/server/server.go, internal/server/services.go
closes https://github.com/odpf/guardian/issues/68
=> feat: migrate to salt mux

internal/store/postgres/resource_repository_test.go
fix flaky test like this one: https://github.com/odpf/guardian/actions/runs/4171185047/jobs/7220864512
=> test(store): fix flaky test due to inconsistent slice

plugins/notifiers/client.go, plugins/notifiers/slack/client.go, plugins/notifiers/slack/client_test.go
* make `slack.Notifier` public
Changes for discussion - https://github.com/odpf/guardian/pull/370#discussion_r1125886870
=> refactor: make slack.Notifier public

api/handler/v1beta1/appeal.go, cli/client.go
- created by was in list appeal filter was getting ignored and should be fixed now
=> fix: list appeal filter for created by
