raystack/guardian

api/handler/v1beta1/adapter.go
domain/policy.go

Closes #87 
- skip validating `Step.Approvers` if value is empty
- parse `Policy.IAM` to be nil if the source value is nil

fix: fix validation errors on policy creation via cli

---

app/server.go

fix: ignore case-sensitivity when matching AUTHENTICATED_USER_HEADER_KEY config value

---

cmd/resource.go
core/policy/service_test.go
domain/policy.go

- fix `view resource` command default format
- rename `expression` field to `when` in yaml and json format
- fix requirement `on` (trigger) and `resource` (identifier) fields validation

fix: fix bugs

---

cmd/policy.go

Policy view command to support both of the ways to pass version:
1. guardian policy view my_policy --version 1
2. guardian policy view my_policy@1

feat: policy view command support version flag

---

Dockerfile

Got `x509: certificate signed by unknown authority` error when fetching to https IAM.
The base image we use `alpine` isn't supporting it hence adding it manually

chore: install ca-certificates to support https fetches which is not supported by alpine

---

cmd/resource.go
core/policy/service.go
core/policy/service_test.go
plugins/providers/bigquery/provider.go
plugins/providers/gcloudiam/provider.go
store/model/appeal.go
store/model/policy.go
store/postgres/policy_repository_test.go

- assign appeal's default values when validating requirements in policy creation
- add missing revoke info fields in model adapter
- store requirements config properly
- ignore "permission exists" error during granting permission to sync the appeal state
- ignore "permission not found" error during revoking permission to sync the appeal state
- change `format` flag to `output` in resource sub-commands

fix: bug fixes

---

api/handler/v1beta1/grpc.go
core/appeal/service.go
core/appeal/service_test.go
domain/appeal.go
domain/approval.go
store/postgres/appeal_repository.go
store/postgres/appeal_repository_test.go

Changes: 
- filter `/me/appeals` endpoints based on `created_by` instead of `account_id`
- terminate existing active appeal when new approval is approved instead of created

fix(appeal): appeal fixes and refactor

---

internal/evaluator/expression.go

> Add string function split to [expr](https://github.com/antonmedv/expr) evaluator.
> This function will help to create an array using string split function
`{
"name": "project_regex", "strategy": "auto", "approve_if": "len(Split($appeal.account_id, ',')) > 1"
}`

feat: add match, split, contains function in expression evaluation

---

Dockerfile

This cert is needed for connectivity with OpenIDM

Fix: Add intermediate certs for OpenIDM SSL connectivity

---

app/config.go
cmd/appeal.go
cmd/client.go
cmd/config.go
cmd/policy.go
cmd/provider.go
cmd/resource.go
cmd/root.go
main.go

closes: #120 
changes:
- added `host` flag for core commands
- load config from file first, if it's not available, read config fields from flags
- refactor: move `app.CLIConfig` struct to `cmd.Config`
any config stored in the file should be override-able via flag too. Currently, there is only `host`

fix(cmd): load `host` from flag for core commands

---

app/config.go
app/server.go
app/services.go
cmd/job.go
cmd/jobs.go
cmd/root.go
core/provider/service.go
store/postgres/resource_repository.go
store/postgres/resource_repository_test.go

closes #140 
usage: `guardian jobs run <job_name>`
example: `guardian jobs run fetch_resources`
valid job names: `fetch_resources`, `appeal_expiration_reminder`, `appeal_expiration_revocation`

feat(cmd): add sub-command for running jobs

---

plugins/notifiers/slack/client.go

At the moment, there is provision to cache slack ID instead of calling the slack api each time for notifications. But the id is not cached due to the missed line of code, which this PR aims to fix.

fix(notifiers): cache slack id

---

jobs/appeal_expiration_reminder.go

fix(jobs): use createdBy instead of accountID for appeal expiry reminder

---

core/appeal/service.go

bug: extending an appeal that is linked to a policy with additional appeals was not working because guardian detected the existing additional appeals already exist. This fix will allow the appeal to be created (activated) even the additional appeals are still active by skipping the additional appeals creation.

fix(appeal): skip creation on appeal duplication error for additional appeals

---

core/appeal/service.go
core/appeal/service_test.go

policy example:
```yaml
...
requirements:
on:
resource_id: 123
appeals:
- resource:
id: 456
role: viewer
policy:
id: policy-x # overriding policy
version: 99
```
the policy (policy-x@99) specified above won't get applied for the additional appeal creation for resource_id:456
this PR is for fixing that bug

fix(appeal): additional appeal policy override

---

internal/store/postgres/approval_repository.go
internal/store/postgres/approval_repository_test.go
plugins/providers/bigquery/config_test.go
plugins/providers/bigquery/provider_test.go
plugins/providers/bigquery/resource_test.go
plugins/providers/gcloudiam/config_test.go
plugins/providers/gcloudiam/provider_test.go
plugins/providers/grafana/client_test.go
plugins/providers/grafana/provider_test.go
plugins/providers/metabase/client_test.go
plugins/providers/metabase/provider_test.go
plugins/providers/noop/provider.go
plugins/providers/tableau/client_test.go
plugins/providers/tableau/provider_test.go

* Instead of fetching approvers first and using a `in` query to fetch approvals, join approvers with approvals table to remove the `in` clause
closes #231

fix: optimize list approvals query

---

core/provider/service.go
core/provider/service_test.go

Closes: #234 
Changes:
* Update provider record with the latest changes always without merging with the existing record
* Fix test case
BREAKING CHANGE: Current provider API works in a patch way although with issues. This change makes sure the provider takes in the latest value only without any merging with the existing value.

feat(provider)!: update provider with the latest value

---

.github/CODEOWNERS
internal/store/postgres/grant_repository.go

fixes an issue from recently merged PR #302: 
- list grants with filter `is_permanent=false` is not working because it's not passed in the repository

fix(grant): fix is_permanent filter condition

---

go.mod
go.sum

- Currently guardian using `cloud.google.com/go/bigquery` which doesn't support authorized UDFs
- When authorized appeal to dataset that have authorized UDFs, it will throw an error `bigquery: invalid access value` 
- Bump `cloud.google.com/go/bigquery` to version `v1.13.0`  which already fixed by this https://github.com/googleapis/google-cloud-go/pull/3084

fix(bigquery): upgrade client to support authorized UDFs

---

go.mod
go.sum

- Relates with https://github.com/odpf/salt/pull/66
- To fix telemetry headers configuration via environment variable

feat: bump salt config version

---

plugins/providers/bigquery/provider.go
plugins/providers/bigquery/provider_test.go

failed test due to map comparison: https://github.com/odpf/guardian/actions/runs/4051388393/jobs/6969667303
Closes #344

test: fix inconsistent test due to unordered slices comparison

---

core/grant/service.go
core/grant/service_test.go
domain/grant.go
domain/provider.go
internal/store/postgres/grant_repository.go
internal/store/postgres/model/resource.go

Changes:
- upsert resources individually in `grantRepository.BulkUpsert` to avoid duplicate resources on upsert
- fix nil pointer exception issue on `sampleGrant` initialization when grouping imported grants by provider role
- prioritize role with most permissions when grouping imported grants

fix(grant): fix bug when grouping imported access

---

core/appeal/service.go
core/appeal/service_test.go

Changes:
- support expression evaluation in policy iam schema config
example:
```json
// response from identity service
{"managers": [{"email": "user@example.com"}]}
```
```yaml
iam:
...
schema:
managers: $response.managers[0].email
```
```go
// appeal result
Appeal{
...
Creator: map[string]interface{}{
"managers": "user@example.com"
},
}
```

feat: allow policy iam config to retrieve value using expression

---

core/appeal/errors.go
core/appeal/service.go
core/appeal/service_test.go
internal/store/postgres/migrations/000014_add_indexes_to_improve_slow_queries.down.sql
internal/store/postgres/migrations/000014_add_indexes_to_improve_slow_queries.up.sql

- The function `getActiveGrantsMap` retrieves all active grants, resulting in slow performance when a large number of records are returned.
- Some queries are slows due to not having an index
- refactored to filter existing active grants in the database instead of retrieving all active data and filtering it on the application side.
- add indexes for slow queries

feat: improve performance

---

plugins/providers/gcs/client.go
plugins/providers/gcs/config.go

fix the following error when parsing principal identifier from gcs iamPolicy
```
failed to import access: fetching access from provider: invalid bucket access member signature "deleted:user:example@example.com?uid=123456"
```

fix(gcs): exclude deleted principals

---

internal/store/postgres/activity_repository_test.go
internal/store/postgres/appeal_repository_test.go
internal/store/postgres/approval_repository_test.go
internal/store/postgres/grant_repository_test.go
internal/store/postgres/policy_repository_test.go
internal/store/postgres/provider_repository_test.go
internal/store/postgres/resource_repository_test.go

try to solve issue #354 so that people using Guardian will have options of disabling store package test which uses dockertest that requires connecting to `/var/run/docker.sock`
```sh
$ go test -count=1 -race -v -short github.com/odpf/guardian/internal/store/postgres
=== RUN   TestActivityRepository
activity_repository_test.go:32:
--- SKIP: TestActivityRepository (0.00s)
=== RUN   TestAppealRepository
appeal_repository_test.go:393:
--- SKIP: TestAppealRepository (0.00s)
=== RUN   TestApprovalRepository
approval_repository_test.go:30:
--- SKIP: TestApprovalRepository (0.00s)
=== RUN   TestGrantRepository
grant_repository_test.go:34:
--- SKIP: TestGrantRepository (0.00s)
=== RUN   TestPolicyRepository
policy_repository_test.go:208:
--- SKIP: TestPolicyRepository (0.00s)
=== RUN …
```

test: add short flag for store unit test because it's using dockertest for integration tests

---

Makefile
core/appeal/service.go
core/provider/service.go
core/provider/service_test.go
core/resource/service.go
core/resource/service_test.go
domain/appeal.go
plugins/providers/bigquery/client.go
plugins/providers/bigquery/client_test.go
plugins/providers/bigquery/config.go
plugins/providers/bigquery/model.go
plugins/providers/bigquery/provider.go
utils/time.go
utils/time_test.go
utils/utils.go

- convert duration to days if possible for slack approval notification
- send appeal rejection notification for auto rejected steps, which got auto-rejected at appeal creation time
- include labels from dataset & table when fetching resources (prevent Resource.Details["_metadata"] update from users in UpdateResource) (#372 )

feat: convert duration to days and appeal rejection notification
